### PR TITLE
Fixing incorrect width

### PR DESCRIPTION
**Pull request by robdmoore**

### CODE REVIEW

**Comment by mderriey** [comment]
Hey @robdmoore, what's with all the changes to the `yarn.lock` file?

The actual changes don't seem to require updating dependencies.

**Comment by TienPhan** [comment]
@robdmoore does this fix include the Managed Services template?

**Comment by robdmoore** [comment]
Should do.

--

**Comment by robdmoore** [comment]
Yeah that was weird. I just ran yarn and it did that, someone mustn’t have run yarn before?

--

**Comment by robdmoore** [comment]
yolo!

**Pull request merged**
