### PR TITLE
Change 'If I've sent it to you by accident'

### PR DESCRIPTION
**Pull request by pmcilreavy**
This a PR for my suggestion raised in issue #59

### CODE REVIEW

**Comment by mderriey** [comment]
No opinion here.

@alice-mx was the one introducing this; any thoughts/opinions?

**Comment by alice-mx** [comment]
I'm always a fan of human readable language over legalese! But also I'm happy for you to put this through

**Comment by pmcilreavy** [comment]
My suggestion of "If you are not the intended recipient, please delete it immediately." is only really the minimum word change I thought I could get away and still maintain the spirit of the original, which I thought was supposed to be _legalese_. 

BUT I would rather have something fun and human-readable, which might be something obviously playful like _"If I've goofed up and you've mistakenly received this email, please be a pal and delete it."_. I dunno we'd want exactly this, but something like it.

If we're actually _trying_ to be playful I feel like we could go further than "If I've sent it to you by accident, please delete it immediately".

**Comment by pmcilreavy** [comment]
meh

**Pull request closed without merging**
